name: CMake

on:
  push:
    branches: [ linux ]
  pull_request:
    branches: [ linux ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: Jimver/cuda-toolkit@v0.2.5
      id: cuda-toolkit
      with:
        cuda: '11.5.1'

    - name: Update submodules
      run: git submodule update --init

    - name: Configure CMake GPU
      run: cmake -B ${{github.workspace}}/build-gpu -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}  -DWITH_GPU=ON

    - name: Build GPU
      run: cmake --build ${{github.workspace}}/build-gpu --config ${{env.BUILD_TYPE}}

    - name: Configure CMake CPU
      run: cmake -B ${{github.workspace}}/build-cpu -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}  -DWITH_GPU=OFF

    - name: Build CPU
      run: cmake --build ${{github.workspace}}/build-cpu --config ${{env.BUILD_TYPE}}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: aquaminer-gpu
        path: ${{github.workspace}}/build-gpu/aquacppminer-gpu

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: aquaminer-cpu
        path: ${{github.workspace}}/build-cpu/aquacppminer-gpu
